name = "nospoilerscores"
compatibility_date = "2026-03-31"
pages_build_output_dir = "out"

[[r2_buckets]]
binding = "DATA"
bucket_name = "hidescore-data"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "hidescore-auth"
database_id = "473a94af-899e-45d4-ba65-3832888c6ab0"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "PICKS"
id = "f088e69fd8dc43e5900a70949e6a5f34"
